# -*- python -*-

from SCons.Script import Environment

env = Environment(tools=['default'])

# allow variant builds to override the default tool name for the logx library
env.Require(env.get('LOGX_TOOL_NAME', 'logx'))

test = env.Program('tlogx', env.Split("""
 tlogx.cc tlogx_a.cc tlogx_b.cc
"""))

env.Alias('check', env.Test(test, env.ChdirActions(["./tlogx --debug all"])))
