# -*- python -*-

env = Environment(tools = ['default','logx'])

env.AppendUnique(CPPPATH="../..")

test = env.Program('tlogx', Split("""
 tlogx.cc tlogx_a.cc tlogx_b.cc
"""))

Alias('check', env.Test(test, env.ChdirActions(["./tlogx"])))
