#!/bin/sh
/usr/local/bin/valgrind  --verbose --gen-suppressions=yes \
--leak-check=full --show-reachable=yes --track-origins=yes \
 --read-var-info=yes  \
--suppressions=${HOME}/valgrind/wt_valgrind_suppressions  \
--vgdb=yes --vgdb-error=0 \
./tlogx
